DROP INDEX EMP_NAME_IX;
DROP INDEX EMPLOYEES_NAME_IDX;
DROP INDEX EMPLOYEES_LAST_NAME_FIRST_NAME_IDX;

SELECT *
FROM EMPLOYEES
WHERE LAST_NAME = 'Fortnite';


CREATE INDEX EMPLOYEES_LAST_NAME_IDX
ON EMPLOYEES (LAST_NAME);
    
SELECT *
FROM EMPLOYEES
WHERE LAST_NAME = 'Fortnite';    


CREATE INDEX EMPLOYEES_LAST_NAME_FIRST_NAME_IDX
ON EMPLOYEES(
    LAST_NAME, 
    FIRST_NAME
);

SELECT *
FROM  EMPLOYEES
WHERE LAST_NAME = 'Fortnite'     AND
      FIRST_NAME = 'Bonequinho';
 
      
ALTER INDEX EMPLOYEES_LAST_NAME_FIRST_NAME_IDX REBUILD;


SELECT IX.INDEX_NAME,
       IC.COLUMN_POSITION,
       IC.COLUMN_NAME,
       IX.INDEX_TYPE,
       IX.UNIQUENESS,
       IX.STATUS
FROM   
    USER_INDEXES IX
JOIN 
    USER_IND_COLUMNS IC ON(IX.INDEX_NAME = IC.INDEX_NAME)AND(IX.TABLE_NAME = IC.TABLE_NAME)
WHERE 
    IX.TABLE_NAME = 'EMPLOYEES'
ORDER BY 
    IX.INDEX_NAME, 
    IC.COLUMN_POSITION; 
