SELECT
     E.EMPLOYEE_ID,
     E.LAST_NAME,
     E.DEPARTMENT_ID,
     D.LOCATION_ID
FROM
     EMPLOYEES   E,
     DEPARTMENTS D
WHERE
     (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
ORDER BY
     E.DEPARTMENT_ID;

SELECT
     E.EMPLOYEE_ID,
     J.JOB_TITLE,
     D.DEPARTMENT_NAME,
     L.CITY,
     L.STATE_PROVINCE,
     L.COUNTRY_ID
FROM
     EMPLOYEES   E,
     JOBS        J,
     DEPARTMENTS D,
     LOCATIONS   L
WHERE
     (E.JOB_ID = J.JOB_ID)
     AND (D.DEPARTMENT_ID = E.DEPARTMENT_ID)
     AND (D.LOCATION_ID = L.LOCATION_ID)
ORDER BY
     E.EMPLOYEE_ID;

SELECT
     E.EMPLOYEE_ID,
     E.SALARY,
     J.JOB_TITLE,
     D.DEPARTMENT_NAME,
     L.CITY,
     L.STATE_PROVINCE,
     L.COUNTRY_ID
FROM
     EMPLOYEES   E,
     JOBS        J,
     DEPARTMENTS D,
     LOCATIONS   L
WHERE
     (E.JOB_ID = J.JOB_ID)
     AND (D.DEPARTMENT_ID = E.DEPARTMENT_ID)
     AND (D.LOCATION_ID = L.LOCATION_ID)
     AND (E.SALARY >= 1000)
ORDER BY
     E.EMPLOYEE_ID;

SELECT
     E.EMPLOYEE_ID,
     E.SALARY,
     J.GRADE_LEVEL,
     J.LOWEST_SAL,
     J.HIGHEST_SAL
FROM
     EMPLOYEES  E,
     JOB_GRADES J
WHERE
     NVL(E.SALARY,
     0) BETWEEN J.LOWEST_SAL
     AND J.HIGHEST_SAL
ORDER BY
     E.SALARY;

SELECT
     E.FIRST_NAME,
     E.LAST_NAME,
     D.DEPARTMENT_ID,
     D.DEPARTMENT_NAME
FROM
     EMPLOYEES   E,
     DEPARTMENTS D
WHERE
     E.DEPARTMENT_ID = D.DEPARTMENT_ID(+)
ORDER BY
     E.DEPARTMENT_ID;

SELECT
     E.FIRST_NAME,
     E.LAST_NAME,
     D.DEPARTMENT_ID,
     D.DEPARTMENT_NAME
FROM
     EMPLOYEES   E,
     DEPARTMENTS D
WHERE
     E.DEPARTMENT_ID(+) = D.DEPARTMENT_ID
ORDER BY
     E.FIRST_NAME;

SELECT
     EMPREGADO.EMPLOYEE_ID "ID EMPREGADO",
     EMPREGADO.LAST_NAME   "SOBRENOME EMPREGADO",
     GERENTE.EMPLOYEE_ID   "ID GERENTE",
     GERENTE.LAST_NAME     "SOBRENOME GERENTE"
FROM
     EMPLOYEES EMPREGADO,
     EMPLOYEES GERENTE
WHERE
     (EMPREGADO.MANAGER_ID = GERENTE.EMPLOYEE_ID)
ORDER BY
     EMPREGADO.EMPLOYEE_ID;

DESC EMPLOYEES

SELECT
     EMPREGADO.EMPLOYEE_ID "ID EMPREGADO",
     EMPREGADO.LAST_NAME   "SOBRENOME EMPREGADO",
     GERENTE.EMPLOYEE_ID   "ID GERENTE",
     GERENTE.LAST_NAME     "SOBRENOME GERENTE"
FROM
     EMPLOYEES EMPREGADO,
     EMPLOYEES GERENTE
WHERE
     (EMPREGADO.MANAGER_ID = GERENTE.EMPLOYEE_ID(+))
ORDER BY
     EMPREGADO.EMPLOYEE_ID;

SELECT
     E.EMPLOYEE_ID,
     E.FIRST_NAME,
     E.LAST_NAME,
     J.JOB_TITLE,
     J.JOB_ID
FROM
     EMPLOYEES E,
     JOBS      J
     SELECT
          E.EMPLOYEE_ID,
          E.FIRST_NAME,
          E.LAST_NAME,
          J.JOB_TITLE,
          J.JOB_ID
     FROM
          EMPLOYEES E,
          JOBS      J
     WHERE
          E.JOB_ID = J.JOB_ID;