-- SEÇÃO 20 - DATABASE DML TRIGGERS
-- AULA 2 - DATABASE DML TRIGGERS A NÍVEL DE COMANDO

-- DATABASE DML TRIGGERS A NÍVEL DE COMANDO

CREATE OR REPLACE TRIGGER B_I_EMPLOYEES_S_TRG
BEFORE INSERT
ON EMPLOYEES
BEGIN
  IF (TO_CHAR(SYSDATE, 'DAY') IN ('SABADO', 'DOMINGO') OR
      TO_NUMBER(TO_CHAR(SYSDATE,'HH24')) NOT BETWEEN 8 AND 18) 
  THEN
       RAISE_APPLICATION_ERROR( -20001, 'O CADASTRAMENTO DE EMPREGADOS SÓ É PERMITIDO EM DIAS DE SEMANA DENTRO DO HORÁRIO COMERCIAL');
  END IF;
END;

-- TESTANDO A VALIDAÇÃO DA TRIGGER

BEGIN
  PCK_EMPREGADOS.PRC_INSERE_EMPREGADO('SHELDON', 'COPPER', 'SLCOPPER', '515.258.5690', SYSDATE, 'IT_PROG', 25000, NULL, 103, 60);
  COMMIT;
END;

-- CRIANDO UMA TRIGGER COMBINANDO VÁRIOS EVENTOS

CREATE OR REPLACE TRIGGER B_IUD_VALIDA_HORARIO_EMPLOYEES_S_TRG
BEFORE INSERT OR UPDATE OR DELETE
ON EMPLOYEES
BEGIN
  IF (TO_CHAR(SYSDATE, 'DAY') IN ('SABADO', 'DOMINGO') OR
      TO_NUMBER(TO_CHAR(SYSDATE,'HH24')) NOT BETWEEN 8 AND 18) 
  THEN
      CASE
        WHEN INSERTING 
        THEN 
             RAISE_APPLICATION_ERROR( -20001, 'O CADASTRAMENTO DE EMPREGADOS SÓ É PERMITIDO EM DIAS DE SEMANA, DENTRO DO HORÁRIO COMERCIAL');
        WHEN DELETING
        THEN 
             RAISE_APPLICATION_ERROR( -20002, 'A DELEÇÃO DE EMPREGADOS SÓ É PERMITIDO EM DIAS DE SEMANA, DENTRO DO HORÁRIO COMERCIAL');
        ELSE
             RAISE_APPLICATION_ERROR( -20003, 'A ATUALIZAÇÃO DE EMPREGADOS SÓ É PERMITIDO EM DIAS DE SEMANA, DENTRO DO HORÁRIO COMERCIAL');
      END CASE;
  END IF;
END;

-- TESTANDO A VALIDAÇÃO DA TRIGGER

BEGIN
  PCK_EMPREGADOS.PRC_INSERE_EMPREGADO('SHELDON', 'COPPER', 'SLCOPPER', '515.258.5690', SYSDATE, 'IT_PROG', 25000, NULL, 103, 60);
  COMMIT;
END;