-- SEÇÃO 14 - PROCEDURES DE BANCO DE DADOS

-- AULA 4 - MÉTODOS DE PASSAGEM DE PARÂMETROS

-- MÉTODOS DE PASSAGEM DE PARÂMETROS

-- MÉTODO POSICIONAL

SET SERVEROUTPUT ON;
SET VERIFY OFF;
DECLARE 
  EMPLOYEES_RECORD EMPLOYEES%ROWTYPE;
BEGIN
  PRC_CONSULTA_EMPREGADO(207, EMPLOYEES_RECORD.FIRST_NAME, EMPLOYEES_RECORD.LAST_NAME, EMPLOYEES_RECORD.EMAIL,
                         EMPLOYEES_RECORD.PHONE_NUMBER, EMPLOYEES_RECORD.HIRE_DATE, EMPLOYEES_RECORD.JOB_ID, 
                         EMPLOYEES_RECORD.SALARY, EMPLOYEES_RECORD.COMMISSION_PCT, EMPLOYEES_RECORD.MANAGER_ID, 
                         EMPLOYEES_RECORD.DEPARTMENT_ID);
  DBMS_OUTPUT.PUT_LINE(EMPLOYEES_RECORD.FIRST_NAME || ' ' || 
                       EMPLOYEES_RECORD.LAST_NAME || ' - ' ||
                       EMPLOYEES_RECORD.DEPARTMENT_ID || ' - ' ||
                       EMPLOYEES_RECORD.JOB_ID || ' - ' ||
                       EMPLOYEES_RECORD.PHONE_NUMBER || ' - ' ||
                       LTRIM(TO_CHAR(EMPLOYEES_RECORD.SALARY, 'L99G999G999D99')));
END;


-- MÉTODO NOMEADO

SET SERVEROUTPUT ON;
SET VERIFY OFF;
DECLARE
  VEMPLOYEE_ID    NUMBER := 207;
  VFIRST_NAME     VARCHAR2(200);
  VLAST_NAME      VARCHAR2(200);
  VEMAIL          VARCHAR2(200);
  VPHONE_NUMBER   VARCHAR2(200);
  VHIRE_DATE      DATE;
  VJOB_ID         VARCHAR2(200);
  VSALARY         NUMBER;
  VCOMMISSION_PCT NUMBER;
  VMANAGER_ID     NUMBER;
  VDEPARTMENT_ID  NUMBER;
BEGIN
  PRC_CONSULTA_EMPREGADO(
    PEMPLOYEE_ID    => VEMPLOYEE_ID,
    PFIRST_NAME     => VFIRST_NAME,
    PLAST_NAME      => VLAST_NAME,
    PEMAIL          => VEMAIL,
    PPHONE_NUMBER   => VPHONE_NUMBER,
    PHIRE_DATE      => VHIRE_DATE,
    PJOB_ID         => VJOB_ID,
    PSALARY         => VSALARY,
    PCOMMISSION_PCT => VCOMMISSION_PCT,
    PMANAGER_ID     => VMANAGER_ID,
    PDEPARTMENT_ID  => VDEPARTMENT_ID
  );

  DBMS_OUTPUT.PUT_LINE('PFIRST_NAME = ' || VFIRST_NAME);
  DBMS_OUTPUT.PUT_LINE('PLAST_NAME = ' || VLAST_NAME);
  DBMS_OUTPUT.PUT_LINE('PEMAIL = ' || VEMAIL);
  DBMS_OUTPUT.PUT_LINE('PPHONE_NUMBER = ' || VPHONE_NUMBER);
  DBMS_OUTPUT.PUT_LINE('PHIRE_DATE = ' || VHIRE_DATE);
  DBMS_OUTPUT.PUT_LINE('PJOB_ID = ' || VJOB_ID);
  DBMS_OUTPUT.PUT_LINE('PSALARY = ' || VSALARY);
  DBMS_OUTPUT.PUT_LINE('PCOMMISSION_PCT = ' || VCOMMISSION_PCT);
  DBMS_OUTPUT.PUT_LINE('PMANAGER_ID = ' || VMANAGER_ID);
  DBMS_OUTPUT.PUT_LINE('PDEPARTMENT_ID = ' || VDEPARTMENT_ID);
END;