-- SEÇÃO 15 - FUNÇÕES DE BANCO DE DADOS
--
-- AULA 1 - CRIANDO FUNÇÕES DE BANCO DE DADOS
--

-- CRIANDO FUNÇÕES DE BANCO DE DADOS

CREATE OR REPLACE FUNCTION FNC_CONSULTA_SALARIO_EMPREGADO
  (PEMPLOYEE_ID   IN NUMBER)
   RETURN NUMBER
IS 
  VSALARY  EMPLOYEES.SALARY%TYPE;
BEGIN
  SELECT SALARY
  INTO   VSALARY
  FROM   EMPLOYEES
  WHERE EMPLOYEE_ID = PEMPLOYEE_ID;
  RETURN (VSALARY);
EXCEPTION
  WHEN NO_DATA_FOUND THEN 
    RAISE_APPLICATION_ERROR(-20001, 'EMPREGADO INEXISTENTE');
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20002, 'ERRO ORACLE ' || SQLCODE || ' - ' || SQLERRM);
END;

-- EXECUTANDO A FUNÇÃO PELO BLOCO PL/SQL

SET SERVEROUTPUT ON
SET VERIFY OFF
ACCEPT PEMPLOYEE_ID PROMPT 'DIGITE O ID DO EMPREGADO: '
DECLARE
  VEMPLOYEE_ID  EMPLOYEES.EMPLOYEE_ID%TYPE := &PEMPLOYEE_ID;
  VSALARY       EMPLOYEES.SALARY%TYPE;
BEGIN
  VSALARY := FNC_CONSULTA_SALARIO_EMPREGADO(VEMPLOYEE_ID);
  DBMS_OUTPUT.PUT_LINE('SALARIO: ' || VSALARY);
END;