-- SEÇÃO 16 - GERENCIANDO PROCEDURES E FUNCTIONS
--
-- AULA 1 - GERENCIANDO PROCEDURES E FUNCTIONS
--

-- GERENCIANDO PROCEDURES E FUNCTIONS

-- CONSULTANDO OBJETOS TIPO PROCEDURE E FUNCTION DO SEU USUÁRIO

DESC USER_OBJECTS

SELECT OBJECT_NAME, OBJECT_TYPE, LAST_DDL_TIME, TIMESTAMP, STATUS
FROM   USER_OBJECTS
WHERE  OBJECT_TYPE IN ('PROCEDURE', 'FUNCTION');

SELECT OBJECT_NAME, OBJECT_TYPE, LAST_DDL_TIME, TIMESTAMP, STATUS
FROM   ALL_OBJECTS
WHERE  OBJECT_TYPE IN ('PROCEDURE', 'FUNCTION');

-- CONSULTANDO OBJETOS INVÁLIDOS DO SCHEMA DO SEU USUÁRIO 

DESC USER_OBJECTS

SELECT OBJECT_NAME, OBJECT_TYPE, LAST_DDL_TIME, TIMESTAMP, STATUS
FROM   USER_OBJECTS
WHERE  STATUS = 'INVALID';

-- CONSULTANDO O CÓDIGO FONTE DE PROCEDURES E FUNÇÕES DO SEU USUÁRIO

DESC USER_SOURCE

SELECT LINE, TEXT
FROM   USER_SOURCE
WHERE  NAME = 'PRC_INSERE_EMPREGADO' AND
       TYPE = 'PROCEDURE'
ORDER BY LINE;

SELECT LINE, TEXT
FROM   USER_SOURCE
WHERE  NAME = 'FNC_CONSULTA_SALARIO_EMPREGADO' AND
       TYPE = 'FUNCTION'
ORDER BY LINE;

-- CONSULTANDO A LISTA DE PARÂMETROS DE PROCEDURES E FUNÇÕES 

DESC PRC_INSERE_EMPREGADO

DESC FNC_CONSULTA_SALARIO_EMPREGADO

-- CONSULTANDO ERROS DE COMPILAÇÃO

-- FORÇANDO UM ERRO DE COMPILAÇÃO

CREATE OR REPLACE FUNCTION FNC_CONSULTA_SALARIO_EMPREGADO
  (PEMPLOYEE_ID   IN NUMBER)
   RETURN NUMBER
IS 
  VSALARY  EMPLOYEES.SALARY%TYPE;
BEGIN
  SELECT SALARY
  INTO   VSALARY
  FROM   EMPLOYEES
  WHERE EMPLOYEE_ID = PEMPLOYEE_ID
  RETURN (VSALARY);
EXCEPTION
  WHEN NO_DATA_FOUND THEN 
      RAISE_APPLICATION_ERROR(-20001, 'EMPREGADO INEXISTENTE');
  WHEN OTHERS THEN
     RAISE_APPLICATION_ERROR(-20002, 'ERRO ORACLE ' || SQLCODE || SQLERRM);
END;

-- CONSULTANDO ERROS DE COMPILAÇÃO - COMANDO SHOW ERRORS

SHOW ERRORS PROCEDURE FNC_CONSULTA_SALARIO_EMPREGADO;

-- CONSULTANDO ERROS DE COMPILAÇÃO - VISÃO USER_ERRORS

DESC USER_ERRORS

COLUMN POSITION FORMAT A4
COLUMN TEXT FORMAT A60
SELECT LINE||'/'||POSITION POSITION, TEXT
FROM   USER_ERRORS
WHERE  NAME = 'FNC_CONSULTA_SALARIO_EMPREGADO'
ORDER BY LINE;
