-- SEÇÃO 17 - GERENCIANDO DEPENDÊNCIAS DE OBJETOS
--
-- AULA 1 - GERENCIANDO DEPENDÊNCIAS DE OBJETOS
--

-- GERENCIANDO DEPENDÊNCIAS DE OBJETOS

-- CONSULTANDO DEPENDÊNCIAS DIRETAS DOS OBJETOS DO SEU SCHEMA UTILIZANDO A VISÃO USER_DEPENDENCIES 

DESC USER_DEPENDENCIES

SELECT *
FROM   USER_DEPENDENCIES
WHERE  REFERENCED_NAME = 'EMPLOYEES' AND
       REFERENCED_TYPE = 'TABLE';
       
-- CONSULTANDO DEPENDÊNCIAS DIRETAS E INDIRETAS DOS OBJETOS DO SEU SCHEMA UTILIZANDO A VISÃO USER_DEPENDENCIES 

SELECT      *
FROM        USER_DEPENDENCIES
START WITH  REFERENCED_NAME = 'EMPLOYEES' AND
            REFERENCED_TYPE = 'TABLE'
CONNECT BY PRIOR  NAME = REFERENCED_NAME AND
                  TYPE = REFERENCED_TYPE;
                  

-- CONSULTANDO DEPENDÊNCIAS DIRETAS E INDIRETAS DOS OBJETOS DE TODOS OS SCHEMAS UTILIZANDO A VISÃO DBA_DEPENDENCIES        

-- CONECTE-SE COMO SYS

DESC DBA_DEPENDENCIES

SELECT      *
FROM        DBA_DEPENDENCIES
START WITH  REFERENCED_OWNER = 'HR' AND
            REFERENCED_NAME = 'EMPLOYEES' AND
            REFERENCED_TYPE = 'TABLE'
CONNECT BY PRIOR  OWNER = REFERENCED_OWNER AND
                  NAME =  REFERENCED_NAME   AND
                  TYPE =  REFERENCED_TYPE;
                  
-- CONSULTANDO OBJETOS INVÁLIDOS DO SCHEMA DO SEU USUÁRIO 

DESC USER_OBJECTS

SELECT OBJECT_NAME, OBJECT_TYPE, LAST_DDL_TIME, TIMESTAMP, STATUS
FROM   USER_OBJECTS
WHERE  STATUS = 'INVALID';
