DECLARE TYPE EMPLOYEE_RECORD_TYPE IS RECORD (
        EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID %TYPE,
        FIRST_NAME EMPLOYEES.FIRST_NAME %TYPE,
        LAST_NAME EMPLOYEES.LAST_NAME %TYPE,
        PHONE_NUMBER EMPLOYEES.PHONE_NUMBER %TYPE,
        JOB_ID EMPLOYEES.JOB_ID %TYPE,
        SALARY EMPLOYEES.SALARY %TYPE
    );
TYPE EMPLOYEES_TABLE_TYPE IS TABLE OF EMPLOYEE_RECORD_TYPE INDEX BY BINARY_INTEGER;
EMPLOYEES_TABLE EMPLOYEES_TABLE_TYPE;
BEGIN
SELECT EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    PHONE_NUMBER,
    JOB_ID,
    SALARY BULK COLLECT INTO EMPLOYEES_TABLE
FROM EMPLOYEES;
FOR I IN EMPLOYEES_TABLE.FIRST..EMPLOYEES_TABLE.LAST LOOP DBMS_OUTPUT.PUT_LINE(
    EMPLOYEES_TABLE(I).EMPLOYEE_ID || ' - ' || EMPLOYEES_TABLE(I).FIRST_NAME || ' - ' || EMPLOYEES_TABLE(I).LAST_NAME || ' - ' || EMPLOYEES_TABLE(I).PHONE_NUMBER || ' - ' || EMPLOYEES_TABLE(I).JOB_ID || ' - ' || TO_CHAR(EMPLOYEES_TABLE(I).SALARY, '99G99G99D99')
);
END LOOP;
END;