SET SERVEROUTPUT ON
SET VERIFY OFF
DECLARE CURSOR EMPLOYEES_CURSOR IS
SELECT *
FROM EMPLOYEES;
-- Declaração do Cursor
EMPLOYEES_RECORD EMPLOYEES_CURSOR %ROWTYPE;
BEGIN
/* Inicializada */
OPEN EMPLOYEES_CURSOR;
-- Abrindo o Cursor
/* Loop */
LOOP FETCH EMPLOYEES_CURSOR INTO EMPLOYEES_RECORD;
-- Fetch do Cursor
EXIT
WHEN EMPLOYEES_CURSOR %NOTFOUND;
DBMS_OUTPUT.PUT_LINE(
    EMPLOYEES_RECORD.EMPLOYEE_ID || ' - ' || EMPLOYEES_RECORD.FIRST_NAME || ' - ' || EMPLOYEES_RECORD.LAST_NAME || ' - ' || EMPLOYEES_RECORD.DEPARTMENT_ID || ' - ' || EMPLOYEES_RECORD.JOB_ID || ' - ' || LTRIM(
        TO_CHAR(EMPLOYEES_RECORD.SALARY, 'L99G999G999D99')
    )
);
END LOOP;
CLOSE EMPLOYEES_CURSOR;
-- Close Cursor
END;
-- Controlando um Cursor Explicíto com WHILE LOOP
SET SERVEROUTPUT ON
SET VERIFY OFF
DECLARE CURSOR EMPLOYEES_CURSOR IS
SELECT *
FROM EMPLOYEES;
-- Declaração do Cursor
EMPLOYEES_RECORD EMPLOYEES_CURSOR %ROWTYPE;
BEGIN
/* Inicializa */
OPEN EMPLOYEES_CURSOR;
-- Abrindo Cursor
FETCH EMPLOYEES_CURSOR INTO EMPLOYEES_RECORD;
-- FETCH do Cursor
/* Loop */
WHILE EMPLOYEES_CURSOR %FOUND LOOP DBMS_OUTPUT.PUT_LINE(
    EMPLOYEES_RECORD.EMPLOYEE_ID || ' - ' || EMPLOYEES_RECORD.FIRST_NAME || ' - ' || EMPLOYEES_RECORD.LAST_NAME || ' - ' || EMPLOYEES_RECORD.DEPARTMENT_ID || ' - ' || EMPLOYEES_RECORD.JOB_ID || ' - ' || EMPLOYEES_RECORD.PHONE_NUMBER || ' - ' || LTRIM(
        TO_CHAR(EMPLOYEES_RECORD.SALARY, 'L99G999G999D99')
    )
);
FETCH EMPLOYEES_CURSOR INTO EMPLOYEES_RECORD;
END LOOP;
CLOSE EMPLOYEES_CURSOR;
-- Close Cursor
END;