SELECT *
FROM USER_OBJECTS
ORDER BY OBJECT_TYPE;
DROP TABLE PROJECTS;
CREATE TABLE PROJECTS (
    PROJECT_ID NUMBER(6) NOT NULL,
    PROJECT_CODE VARCHAR2(10) NOT NULL,
    PROJECT_NAME VARCHAR2(100) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    STATUS VARCHAR2(20) NOT NULL,
    PRIORITY VARCHAR2(10) NOT NULL,
    BUDGET NUMBER(11, 2) NOT NULL,
    DESCRIPTION VARCHAR2(400) NOT NULL
);
DESC PROJECTS;
SELECT *
FROM PROJECTS;
DROP TABLE TEAMS;
CREATE TABLE TEAMS (
    PROJECT_ID NUMBER(6) NOT NULL,
    EMPLOYEE_ID NUMBER(6) NOT NULL
);
DESC TEAMS;
DESC EMPLOYEES
SELECT EMPLOYEE_ID,
    FIRST_NAME,
    ROWID,
    LENGTH(ROWID)
FROM EMPLOYEES
WHERE ROWID = 'AAASh6AAMAAAADOAAK';
DESC USER_TABLES
SELECT TABLE_NAME
FROM USER_TABLES;
SELECT OBJECT_NAME,
    OBJECT_TYPE
FROM USER_OBJECTS
WHERE OBJECT_TYPE = 'TABLE';
CREATE TABLE EMPLOYEES_DEPARMENT60 AS
SELECT EMPLOYEE_ID,
    LAST_NAME,
    SALARY * 12 ANNSAL,
    HIRE_DATE
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;
SELECT *
FROM EMPLOYEES_DEPARMENT60;
DESC EMPLOYEES_DEPARMENT60 DROP TABLE EMPLOYEES_DEPARMENT60;
SELECT *
FROM EMPLOYEES_DEPARMENT60;
SELECT *
FROM SYS.USER_RECYCLEBIN
ALTER TABLE PROJECTS
ADD(DEPARTMENT_ID NUMBER(3));
DESC PROJECTS
ALTER TABLE PROJECTS DROP COLUMN DEPARTMENT_ID;
DESC PROJECTS
ALTER TABLE PROJECTS
ADD(DEPARTMENT_ID NUMBER(5) NOT NULL);
DESC PROJECTS
ALTER TABLE PROJECTS
MODIFY (PROJECT_CODE VARCHAR2 (6));
DESC PROJECTS
ALTER TABLE PROJECTS
    RENAME COLUMN PROJECT_NAME TO NOME;
DESC PROJECTS
ALTER TABLE EMPLOYEES READ ONLY;
ALTER TABLE EMPLOYEES READ WRITE;