-- EXCEÇÕES DEFINIDAS PELO DESENVOLVEDOR

SET SERVEROUTPUT ON;
SET VERIFY OFF;
ACCEPT PEMPLOYEE_ID PROMPT 'DIGITE O ID DO EMPREGADO: ';

DECLARE
   VFIRST_NAME    EMPLOYEES.FIRST_NAME%TYPE;
   VLAST_NAME     EMPLOYEES.LAST_NAME%TYPE;
   VJOB_ID        EMPLOYEES.JOB_ID%TYPE;
   VEMPLOYEE_ID   EMPLOYEES.EMPLOYEE_ID%TYPE := &PEMPLOYEE_ID;
   EPRESIDENT     EXCEPTION;

BEGIN
   SELECT FIRST_NAME, LAST_NAME, JOB_ID
   INTO   VFIRST_NAME, VLAST_NAME, VJOB_ID
   FROM   EMPLOYEES
   WHERE  EMPLOYEE_ID = VEMPLOYEE_ID;

   IF VJOB_ID = 'AD_PRES' THEN
      RAISE EPRESIDENT;  
   END IF;

EXCEPTION
   WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20001, 'EMPREGADO NÃO ENCONTRADO, ID = ' || 
      TO_CHAR(VEMPLOYEE_ID));
   WHEN EPRESIDENT THEN
      UPDATE EMPLOYEES
      SET    SALARY = SALARY * 1.5
      WHERE  EMPLOYEE_ID = VEMPLOYEE_ID;
      COMMIT;
   WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20002, 'ERRO ORACLE ' || SQLCODE || SQLERRM);
END;

