-- SEÇÃO 20 - DATABASE DML TRIGGERS
--
-- AULA 4 - REGRAS DE MUTATING TABLES
--

-- REGRAS DE MUTATING TABLES

-- VIOLAÇÃO DA REGRA 1 DE MUTATING TABLE

/*
REGRA 1 DE MUTATING TABLES: NÃO ALTERE DADOS EM COLUNAS DE CHAVES PRIMÁRIAS, 
CHAVES ESTRANGEIRAS OU CHAVES ÚNICAS DE TABELAS RELACIONADAS ÀQUELA NA QUAL 
A TRIGGER DISPARADA ESTÁ ASSOCIADA
*/

CREATE OR REPLACE TRIGGER A_I_EMPLOYEES_R_TRG
AFTER INSERT 
ON EMPLOYEES
FOR EACH ROW
BEGIN
  UPDATE EMPLOYEES
  SET    EMAIL = UPPER(SUBSTR(:NEW.FIRST_NAME,1,1) || :NEW.LAST_NAME)
  WHERE  EMPLOYEE_ID = :NEW.EMPLOYEE_ID;
END;

-- TESTANDO VIOLAÇÃO DA REGRA 1 

SET VERIFY OFF
BEGIN
  PRC_INSERE_EMPREGADO('ERIC', 'CLAPTON','ECLAPTON','515.188.4861',SYSDATE,'IT_PROG',15000,NULL,103,60);
  COMMIT;
END;

-- CORRIGINDO A TRIGGER PARA QUE NÃO VIOLE A REGRA 1

CREATE OR REPLACE TRIGGER A_I_EMPLOYEES_R_TRG
BEFORE INSERT 
ON EMPLOYEES
FOR EACH ROW
BEGIN
  :NEW.EMAIL := UPPER(SUBSTR(:NEW.FIRST_NAME,1,1) || (:NEW.LAST_NAME));
END;

-- TESTANDO A CORREÇÃO DA VIOLAÇÃO DA REGRA 1 
SET VERIFY OFF
BEGIN
  PRC_INSERE_EMPREGADO('ERIC', 'CLAPTON','ECLAPTON','515.188.4861',SYSDATE,'IT_PROG',15000,NULL,103,60);
  COMMIT;
END;

-- VIOLAÇÃO DA REGRA 2 DE MUTATING TABLE

/*
REGRA 2 DE MUTATING TABLES: NÃO LEIA INFORMAÇÕES DE TABELAS QUE ESTEJAM SENDO MODIFICADAS
*/

CREATE OR REPLACE TRIGGER B_U_VALIDATE_SALARY_EMPLOYEES_R_TRG
BEFORE UPDATE OF SALARY
ON  EMPLOYEES
FOR EACH ROW
DECLARE
  VMAXSALARY  EMPLOYEES.SALARY%TYPE;
BEGIN
  SELECT MAX(SALARY)
  INTO   VMAXSALARY
  FROM   EMPLOYEES;

  IF  :NEW.SALARY > VMAXSALARY * 1.2 
  THEN  
      RAISE_APPLICATION_ERROR(-20001, 'SALÁRIO NÃO PODE SER SUPERIOR AO MAIOR SALÁRIO + 20%');
  END IF;
END;

-- TESTANDO VIOLAÇÃO DA REGRA 2 

SET VERIFY OFF
UPDATE EMPLOYEES
SET    SALARY = 70000
WHERE  EMPLOYEE_ID = 100;

COMMIT;

DROP TRIGGER A_I_EMPLOYEES_R_TRG;

DROP TRIGGER B_U_VALIDATE_SALARY_EMPLOYEES_R_TRG;

-- RESOLVENDO O PROBLEMA DE MUTATING TABLES

CREATE OR REPLACE PACKAGE PCK_EMPLOYEES_DADOS 
AS
  TYPE MAX_SALARY_TABLE_TYPE IS TABLE OF NUMBER(10,2)
  INDEX BY BINARY_INTEGER;
  
  GMAXSALARY  MAX_SALARY_TABLE_TYPE;

END PCK_EMPLOYEES_DADOS;

CREATE OR REPLACE TRIGGER B_IU_VALIDATE_SALARY_EMPLOYEES_S_TRG
BEFORE INSERT OR UPDATE OF SALARY
ON  EMPLOYEES
DECLARE
  VMAXSALARY  EMPLOYEES.SALARY%TYPE;
BEGIN
  SELECT MAX(SALARY)
  INTO   PCK_EMPLOYEES_DADOS.GMAXSALARY(1)
  FROM   EMPLOYEES;
END;

CREATE OR REPLACE TRIGGER B_IU_VALIDATE_SALARY_EMPLOYEES_R_TRG
BEFORE INSERT OR UPDATE OF SALARY
ON  EMPLOYEES
FOR EACH ROW
DECLARE
  VMAXSALARY  EMPLOYEES.SALARY%TYPE;
BEGIN
  IF  :NEW.SALARY  > PCK_EMPLOYEES_DADOS.GMAXSALARY(1) * 1.2
  THEN  
      RAISE_APPLICATION_ERROR(-20001, 'NOVO SALÁRIO NÃO PODE SER SUPERIOR AO MAIOR SALÁRIO + 20%');
  END IF;
END;

-- TESTANDO VIOLAÇÃO DA REGRA 2 

SET VERIFY OFF
UPDATE EMPLOYEES
SET SALARY = 30000
WHERE EMPLOYEE_ID = 100;

COMMIT;
