-- Removendo Procedure de Banco de Dados

DROP PROCEDURE PRC_CONSULTA_EMPREGADO;


-- Criando novamente para concluir o curso

CREATE OR REPLACE PROCEDURE PRC_CONSULTA_EMPREGADO
  (PEMPLOYEE_ID   IN NUMBER,
   PFIRST_NAME    OUT NOCOPY VARCHAR2,
   PLAST_NAME     OUT NOCOPY VARCHAR2,
   PEMAIL         OUT NOCOPY VARCHAR2,
   PPHONE_NUMBER  OUT NOCOPY VARCHAR2,
   PHIRE_DATE     OUT NOCOPY DATE,
   PJOB_ID        OUT NOCOPY VARCHAR2,
   PSALARY        OUT NOCOPY NUMBER,
   PCOMMISSION_PCT OUT NOCOPY NUMBER,
   PMANAGER_ID    OUT NOCOPY NUMBER,
   PDEPARTMENT_ID OUT NOCOPY NUMBER)
IS 
BEGIN
  SELECT
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANAGER_ID,
    DEPARTMENT_ID
  INTO 
    PFIRST_NAME,
    PLAST_NAME,
    PEMAIL,
    PPHONE_NUMBER,
    PHIRE_DATE,
    PJOB_ID,
    PSALARY,
    PCOMMISSION_PCT,
    PMANAGER_ID,
    PDEPARTMENT_ID
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID = PEMPLOYEE_ID;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
     RAISE_APPLICATION_ERROR(-20001, 'EMPREGADO NÃO EXISTE: ' || PEMPLOYEE_ID);
  WHEN OTHERS THEN
     RAISE_APPLICATION_ERROR(-20002, 'ERRO ORACLE ' || SQLCODE || SQLERRM);
END;