-- Aula 1 - Tratamento de Exceções

-- Tratamento de Exceções Pré-definidas Oracle

SET SERVEROUTPUT ON;
SET VERIFY OFF;
ACCEPT PEMPLOYEE_ID PROMPT 'DIGITE O ID DO EMPREGADO: ';

DECLARE
  VFIRST_NAME   EMPLOYEES.FIRST_NAME%TYPE;
  VLAST_NAME    EMPLOYEES.LAST_NAME%TYPE;
  VEMPLOYEE_ID  EMPLOYEES.EMPLOYEE_ID%TYPE := &PEMPLOYEE_ID;

BEGIN
  SELECT FIRST_NAME, LAST_NAME
  INTO   VFIRST_NAME, VLAST_NAME
  FROM   EMPLOYEES
  WHERE  EMPLOYEE_ID = VEMPLOYEE_ID;

  DBMS_OUTPUT.PUT_LINE('EMPREGADO: ' || VFIRST_NAME || ' ' || VLAST_NAME);
  
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20001, 'EMPREGADO NÃO ENCONTRADO, ID = ' || 
    TO_CHAR(VEMPLOYEE_ID));
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20002, 'ERRO ORACLE - ' || SQLCODE || ' - ' || SQLERRM);
END;



