-- Utilizando o comando SELECT no PL/SQL

SET SERVEROUTPUT ON 

DECLARE
    vFIRST_NAME       EMPLOYEES.FIRST_NAME%TYPE;
    vLAST_NAME        EMPLOYEES.LAST_NAME%TYPE;
    vSALARY           EMPLOYEES.SALARY%TYPE;
    vEMPLOYEE_ID      EMPLOYEES.EMPLOYEE_ID%TYPE := 121;
BEGIN
    SELECT FIRST_NAME, LAST_NAME, SALARY
    INTO vFIRST_NAME, vLAST_NAME, vSALARY
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = vEMPLOYEE_ID;
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE ID: ' ||
    vEMPLOYEE_ID);
    DBMS_OUTPUT.PUT_LINE('FIRST NAME: ' ||
    vFIRST_NAME);
    DBMS_OUTPUT.PUT_LINE('LAST NAME: ' ||
    vLAST_NAME);
    DBMS_OUTPUT.PUT_LINE('SALARY: ' ||
    vSALARY);
END;

-- Erro ORA-01403 - No Data Found

DECLARE
    vFIRST_NAME       EMPLOYEES.FIRST_NAME%TYPE;
    vLAST_NAME        EMPLOYEES.LAST_NAME%TYPE;
    vSALARY           EMPLOYEES.SALARY%TYPE;
    vEMPLOYEE_ID      EMPLOYEES.EMPLOYEE_ID%TYPE := 50;
BEGIN
    SELECT FIRST_NAME, LAST_NAME, SALARY
    INTO vFIRST_NAME, vLAST_NAME, vSALARY
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = vEMPLOYEE_ID;
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE ID: ' ||
    vEMPLOYEE_ID);
    DBMS_OUTPUT.PUT_LINE('FIRST NAME: ' ||
    vFIRST_NAME);
    DBMS_OUTPUT.PUT_LINE('LAST NAME: ' ||
    vLAST_NAME);
    DBMS_OUTPUT.PUT_LINE('SALARY: ' ||
    vSALARY);
END;

-- Funções de Grupo 

DECLARE
    vJOB_ID       EMPLOYEES.JOB_ID%TYPE :='IT_PROG';
    vAVG_SALARY   EMPLOYEES.SALARY%TYPE;
    vSUM_SALARY   EMPLOYEES.SALARY%TYPE;
BEGIN
    SELECT ROUND(AVG(SALARY),2), ROUND(SUM(SALARY),2)
    INTO vAVG_SALARY, vSUM_SALARY
    FROM EMPLOYEES
    WHERE JOB_ID = vJOB_ID;
    DBMS_OUTPUT.PUT_LINE('CARGO: ' ||
    vJOB_ID);
    DBMS_OUTPUT.PUT_LINE('MÉDIA DE SALÁRIOS: ' ||
    vAVG_SALARY);
    DBMS_OUTPUT.PUT_LINE('SOMATORIO DE SALÁRIOS: ' ||
    vSUM_SALARY);
END;

-- Erro ORA -01422 - Too Many Rows

DECLARE
    vJOB_ID       EMPLOYEES.JOB_ID%TYPE;
    vAVG_SALARY   EMPLOYEES.SALARY%TYPE;
    vSUM_SALARY   EMPLOYEES.SALARY%TYPE;
BEGIN
    SELECT ROUND(AVG(SALARY),2), ROUND(SUM(SALARY),2)
    INTO vAVG_SALARY, vSUM_SALARY
    FROM EMPLOYEES
    GROUP BY JOB_ID;
    DBMS_OUTPUT.PUT_LINE('CARGO: ' ||
    vJOB_ID);
    DBMS_OUTPUT.PUT_LINE('MÉDIA DE SALÁRIOS: ' ||
    vAVG_SALARY);
    DBMS_OUTPUT.PUT_LINE('SOMATORIO DE SALÁRIOS: ' ||
    vSUM_SALARY);
END;


-- Utilizando o comando INSERT no PL/SQL

DECLARE
    vFIRST_NAME  EMPLOYEES.FIRST_NAME%TYPE;
    vLAST_NAME   EMPLOYEES.LAST_NAME%TYPE;
    vSALARY      EMPLOYEES.SALARY%TYPE;
BEGIN 
    INSERT INTO EMPLOYEES (
    EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE,
    JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID
    )
    VALUES (
    EMPLOYEES_SEQ.NEXTVAL, 'CRASH', 'BANDICOOT', 'CRBAOOT','997.843.8423', SYSDATE,
    'IT_PROG', 150000, 0.4, 214, 60);   
COMMIT;
END;
    
-- Utilizando o comando UPDATE no PL/SQL    

DECLARE
    vEMPLOYEE_ID  EMPLOYEES.EMPLOYEE_ID%TYPE := 207;
    vPERCENTUAL   NUMBER(3) := 10;
BEGIN
    UPDATE EMPLOYEES
    SET SALARY = SALARY * (3 + vPERCENTUAL / 100)
    WHERE EMPLOYEE_ID = vEMPLOYEE_ID;
COMMIT;
END;

-- Utilizando o comando DELETE no PL/SQL

DECLARE 
    vEMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE := 212;
BEGIN
    DELETE FROM EMPLOYEES
    WHERE EMPLOYEE_ID = vEMPLOYEE_ID;
    COMMIT;
END;