SET SERVEROUTPUT ON
SET VERIFY OFF

ACCEPT PEMPLOYEE_ID PROMPT 'Digite o Id do empregado: ';

DECLARE
  TYPE EMPLOYEE_RECORD_TYPE IS RECORD (
    EMPLOYEE_ID   EMPLOYEES.EMPLOYEE_ID%TYPE,
    FIRST_NAME    EMPLOYEES.FIRST_NAME%TYPE,
    LAST_NAME     EMPLOYEES.LAST_NAME%TYPE,
    EMAIL         EMPLOYEES.EMAIL%TYPE,
    PHONE_NUMBER  EMPLOYEES.PHONE_NUMBER%TYPE
  );

  EMPLOYEE_RECORD EMPLOYEE_RECORD_TYPE;
    
BEGIN
  SELECT
    EMPLOYEE_ID, 
    FIRST_NAME, 
    LAST_NAME, 
    EMAIL,
    PHONE_NUMBER
  INTO EMPLOYEE_RECORD
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID = &PEMPLOYEE_ID;

  DBMS_OUTPUT.PUT_LINE(
    EMPLOYEE_RECORD.EMPLOYEE_ID || ' - ' ||
    EMPLOYEE_RECORD.FIRST_NAME || ' - ' ||
    EMPLOYEE_RECORD.LAST_NAME || ' - ' ||
    EMPLOYEE_RECORD.PHONE_NUMBER
  );
END;
