DROP VIEW VEMPLOYEESDEPT60;
CREATE OR REPLACE VIEW VEMPLOYEESDEPT60 AS
SELECT EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    DEPARTMENT_ID,
    SALARY,
    COMMISSION_PCT
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;
DESC VEMPLOYEESDEPT60
SELECT *
FROM VEMPLOYEESDEPT60;
DROP VIEW VDEPARTMENTS_TOTAL;
CREATE OR REPLACE VIEW VDEPARTMENTS_TOTAL (
        DEPARTMENT_ID,
        DEPARTMENT_NAME,
        MINSAL,
        MAXSAL,
        AVGSAL
    ) AS
SELECT E.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    MIN(E.SALARY),
    MAX(E.SALARY),
    AVG(E.SALARY)
FROM EMPLOYEES E
    JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
GROUP BY E.DEPARTMENT_ID,
    DEPARTMENT_NAME;
SELECT *
FROM VDEPARTMENTS_TOTAL;
DROP VIEW VEMPLOYEESDEPT100;
CREATE OR REPLACE VIEW VEMPLOYEESDEPT100 AS
SELECT EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    DEPARTMENT_ID,
    SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100 WITH CHECK OPTION CONSTRAINT VEMPLOYEESDEPT100_CK;
CREATE OR REPLACE VIEW VEMPLOYEESDEPT20 AS
SELECT EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    DEPARTMENT_ID,
    SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20 WITH READ ONLY;